version: 0.0
os: linux
files:
  - source: /
    destination: /opt/sample/test
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: dev
  AfterInstall:
    - location: permissions.sh
      timeout: 300
      runas: dev
  ApplicationStart:
    - location: server_start.sh
      timeout: 300
      runas: dev
