---
version: 0
os: linux
files:
  - source: /
    destination: /home/ubuntu/test
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 300
      runas: root
